spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: voting-system
  datasource:
    url: jdbc:postgresql://localhost:5432/voting-system
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
    show-sql: true
server:
  port: 8083

